### ISSUE TITLE
Edge 17- ReferenceError: 'globalThis' is not defined

### ISSUE THREAD

**Issue by yann-combarnous** [zxing-js/browser#18] opened 2020-12-01 13:25 UTC
"@zxing/browser": "^0.0.5",
    "@zxing/library": "^0.18.3",

When using this library under Edge 17, I am getting a reference error :

```
ReferenceError: 'globalThis' is not defined
at @zxing/browser/umd/zxing-browser.js: 65
```

<img width="1061" alt="Screenshot 2020-12-01 at 14 26 59" src="https://user-images.githubusercontent.com/39089766/100746664-4d272000-33e1-11eb-885d-4a22aee080fa.png">

**Comment by yann-combarnous** [comment] 2020-12-01 13:28
Note that using directly @zxing/library does not cause any problem.

**Comment by yann-combarnous** [comment] 2020-12-01 13:37
@odahcam , looks like an issue with the "context" variable in rollup.config.js to me, what do you think? Would be great to have the minimum browser requirements as well, similar to zxing/library.

**Comment by odahcam** [comment] 2020-12-01 15:13
Will Microsoft and it's browsers never stop breaking JavaScript libraries? I don't think so.

This approach using `globalThis || ...` should already solve that, as it does not we gonna need to ponyfill the access of the global object by the library. Well, it's not gonna be THAT fast to solve, we gonna need to at least create a function that returns the "globalThis" and has lots of `typeof` inside.

**Comment by yann-combarnous** [comment] 2020-12-01 17:55
Yes, legacy browser support is a pain, but legacy Edge will slowly and eventually gonna die.

**Comment by karen-m-o** [comment] 2020-12-10 04:14
I am also having this issue on Microsoft Edge 44.18362.449.0 (Microsoft EdgeHTML 18.18363). 
Currently using "@zxing/browser": "0.0.5",

**Comment by odahcam** [comment] 2021-01-27 04:56
Closing as this is dupe of #18.

**Comment by odahcam** [comment] 2021-01-27 04:57
Closing as fixed

**Closed by odahcam** 2021-01-27 04:56 UTC
