### ISSUE TITLE
Uncaught ReferenceError: globalThis is not defined

### ISSUE THREAD

**Issue by oncethor** [zxing-js/browser#26] opened 2020-12-10 11:24 UTC
Hello, I am trying to use the latest version of the library(@zxing/library v0.18.3), but while this works very well on the live demo on the latest Chrome 87, I have problems using it on Chrome + WebView on Android 7.x.

I get "**ReferenceError: globalThis is not defined**" and the page fails to load.
The code is very simple, and I am trying to decode a QR code from the camera, using this code:
```
    const codeReader = new BrowserQRCodeReader();
    codeReader.listVideoInputDevices().then(videoInputDevices => {
       ...
      codeReader.decodeOnceFromVideoDevice(firstDeviceId, 'video').then(
       ...
     );
    }
```

On the same Android environment I am successfully using the "@zxing/library": "^0.17.1" older version and the above code works well.

I haven't tried any of the other 0.18+ versions

**Comment by odahcam** [comment] 2020-12-18 03:49
I would like to link the commit f25cdf7721eab21c97100c9eba980c22c15b3967

**Comment by odahcam** [comment] 2021-01-27 04:56
Closing as this is dupe of #18.

**Closed by odahcam** 2021-01-27 04:56 UTC
