### ISSUE TITLE
How to cancel decodeOnceFromVideoDevice

### ISSUE THREAD

**Issue by thisconnect** [zxing-js/browser#38] opened 2021-01-29 17:55 UTC
I'm trying to migrate from `@zxing/library` to `@zxing/browser` and abort the video is there an api?

This looks related https://github.com/zxing-js/browser/issues/28

**Comment by thisconnect** [comment] 2021-01-29 17:57
FYI in `@zying/library` there was `codeReader.reset()`

**Comment by odahcam** [comment] 2021-02-01 21:50
Dupe of #21

**Closed by odahcam** 2021-02-01 21:50 UTC
