### ISSUE TITLE
Camera randomly shuts off while decoding continuously

### ISSUE THREAD

**Issue by DarrenWainwright** [zxing-js/browser#22] opened 2020-12-08 19:43 UTC
Using: "@zxing/browser": "0.0.5"
Codebase: TypeScript project using lit-element

when trying to decode continuously, using the code below, I am finding that the camera randomly shuts off and ends decoding. 

Seems to happen as I get closer to the barcode being scanned.

Happens on both Edge, Chrome on desktop and Chrome on Android

Am i doing something wrong here?

```
async decodeContinuously(codeReader: BrowserPDF417Reader, selectedDeviceId: string) {
   const videoElem = this.shadowRoot?.getElementById('video');
   this.controls =  await codeReader.decodeFromVideoDevice(selectedDeviceId, videoElem, (result, error, controls)=>{
     if (result){
       console.log(result);
     }
     // TODO - handle exceptions
   });
}
```

**Comment by odahcam** [comment] 2020-12-11 01:26
Related #21

**Comment by odahcam** [comment] 2020-12-11 01:27
Caused by the same reason as #23, so closing this as there we are closer to the root cause.

**Closed by odahcam** 2020-12-11 01:27 UTC
